### PR TITLE
New suggested design

### PR DESCRIPTION
**Pull request by elle**
Still to do: mobile styles

goruco-2018-new-design

### CODE REVIEW

**Comment by jcn** [comment]
This looks amazing! I have some questions:

* The more expensive sponsors should probably have bigger logos (I know, I know, make the logo bigger)
* Does this layout work with more than the existing sponsor logos? We might end up with more gold sponsors (maybe 2 more) and I know we just landed another Bronze and might have to wrap onto a new line. Maybe we just center the "Sponsors" headers like all the other headers and just stack them?
* Where are the talk descriptions? Are they still popping up in modals? I didn't see them in the diff - I feel like those are more important than the speaker bios. Perhaps we can set it up like 2017.goruco.com where a truncated abstract is on the page and pops up the modal with the abstract and the bio? Of course if there's a clear reason for doing it this way, I'd love to hear that too

**Comment by rosscooperman** [comment]
Wow, amazing job, looks fantastic.

~Ross

Sent via Superhuman ( https://sprh.mn/?vip=cooperman@gmail.com )

**Comment by lukemelia** [comment]
Love it!

One note: I don't think we should desaturate sponsor logos.

**Comment by abelmartin** [comment]
I think this looks amazing.  Unfortunately with the changes proposed the new site can't live along side the current site on http://goruco.com/beta, but I think it's a fresh and clean look.  @elle, do you need help with mobile web or are you going to hand it yourself?

**Comment by elle** [comment]
@jcn:
- Will adjust for different logo sizes
- Can accomodate more sponsor logos in the current layout
- Will change bios for talk title and description

@lukemelia: I would very much prefer to keep them grayscale, but if you insist, changing them to colour is removing one css rule.

@abelmartin: I will make the small changes today but don't have time to work on the mobile styles until tomorrow. If we can wait a couple of days, I can do that. Otherwise, feel free to jump in.

I would love to do a bit more tweaking to small things, but will have to be in a day or two, and can be done later...

Thanks everyone

**Comment by jcn** [comment]
Hi @elle -  I believe we're moving forward with this design; is there anything else needed at this point to move ahead?

**Comment by abelmartin** [comment]
Hey @elle, I see the issues with the mobile version of the page.  You stripped out the bootstrap classes that would normally apply a responsive layout.  I'll start working on mobile.

**Comment by abelmartin** [comment]
We also lost the modals that open with the "talk" descriptions.  I'll try to get to that after I handle mobile web

**Comment by elle** [comment]
Mobile styles are pretty much done. And yes, not us my bootstrap. Will push up in the next couple hours

**Comment by abelmartin** [comment]
Oh great!  Then I'll work on the modal later tonight

**Comment by jcn** [comment]
@abelmartin https://github.com/goruco/goruco2018/pull/25/files is the commit for the modal popup. It has two parts:

1. The ids of the speaker div is the slugified version of the speaker's name
2. The JS pops open the modal if there's a page anchor on page load and on modal close it clears the  anchor

**Comment by elle** [comment]
So far:
1. sponsors area allows for more logos and logos' sizes have been adjusted according to sponsorship level.
2. Speaker's bio was changed to talk title and description
3. Small screen styles have been done, but there still need to be adjustments for mid-size screens (ie. iPads)

I would rather not Implement the modals. So if that's ok with everyone, will merge this merge to `gh-pages` branch and @abelmartin can take it from there.

**Comment by jcn** [comment]
@elle Since merging into `gh-pages` will push it live it seems like it'd be best for @abelmartin to make the changes on this branch first and then merge when it's ready to go. 

Also, if we wanted to include both the talk into and the speaker bio in the modal, do you have a recommendation of what styles we might use for that?

**Comment by elle** [comment]
You’re right. I should really merge this with master.

**Comment by abelmartin** [comment]
Merged :-D

After I complete the modals, we'll merge to `gh-pages`.

**Pull request merged**
